<?php

namespace Tests;

use App\Http\Repositories\LeagueMatchRepository;
use App\Http\Repositories\TeamRepository;
use App\Models\LeagueMatch;
use App\Models\Team;
use App\Services\MatchService;
use App\Services\Scheduler\Scheduler;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Testing\TestResponse;
use Throwable;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use DatabaseMigrations;

    /**
     * {@inheritDoc}
     * @throws Throwable
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed();

        $matchService = new MatchService(new LeagueMatchRepository(new LeagueMatch()), new TeamRepository(new Team()), new Scheduler());
        if (!$matchService->fixtureIsGenerated()) {
            $matchService->generateFixture();
        }
    }

    /**
     * Make ajax POST JSON request.
     * @param string $uri
     * @param array $data
     * @param array $headers
     * @return TestResponse
     */
    public function ajaxPostJson(string $uri, array $data, array $headers = []): TestResponse
    {
        $ajaxHeaders = ['HTTP_X-Requested-With' => 'XMLHttpRequest'];

        return $this->postJson($uri, $data, array_merge($ajaxHeaders, $headers));
    }
}
