<?php

namespace Tests;

use App\Http\Repositories\LeagueMatchRepository;
use App\Http\Repositories\TeamRepository;
use App\Models\LeagueMatch;
use App\Models\Team;
use App\Services\MatchService;
use App\Services\Scheduler\Scheduler;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Throwable;

class UnitTestCase extends BaseTestCase
{
    use CreatesApplication;
    use DatabaseMigrations;

    /**
     * @var MatchService
     */
    protected MatchService $matchService;

    /**
     * {@inheritDoc}
     * @throws Throwable
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->matchService = $matchService = new MatchService(new LeagueMatchRepository(new LeagueMatch()), new TeamRepository(new Team()), new Scheduler());
    }
}
